services:
  my-postgres:
    image: postgres:16
    container_name: my-postgres
    restart: always
    environment:
      POSTGRES_DB: springAuth
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pleasecomein
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: egorapotcha@gmail.com
      PGADMIN_DEFAULT_PASSWORD: pleasecomein
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  my-keycloak:
    image: keycloak/keycloak:22.0.5
    container_name: my-keycloak
    restart: always
    depends_on:
      my-postgres:
        condition: service_healthy
    environment:
      spi-event-listener-custom-event-listener-webhookUrl: http://192.168.100.248:8081/keycloak-events/user-updated
      spi-event-listener-custom-event-listener-secretKey: keycloak_secret
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD : admin
    ports:
      - "8080:8080"
    volumes:
      - ./keycloak-custom-providers-2.2.3-SNAPSHOT-jar-with-dependencies.jar:/opt/keycloak/providers/keycloak-custom44.jar
      - ./realms/realm-export.json:/opt/keycloak/data/import/realm-export.json
    command:
      - "start-dev"
      - "--import-realm"

volumes:
  postgres-data:
  pgadmin-data:
