--
-- PostgreSQL database dump
--

-- Dumped from database version 16.6 (Debian 16.6-1.pgdg120+1)
-- Dumped by pg_dump version 16.6 (Debian 16.6-1.pgdg120+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: task; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.task (
    id integer NOT NULL,
    description character varying(255),
    header character varying(255),
    priority character varying(255),
    status character varying(255),
    author_id text NOT NULL,
    CONSTRAINT task_priority_check CHECK (((priority)::text = ANY ((ARRAY['HIGH'::character varying, 'MEDIUM'::character varying, 'LOW'::character varying])::text[]))),
    CONSTRAINT task_status_check CHECK (((status)::text = ANY ((ARRAY['InProgress'::character varying, 'Completed'::character varying, 'Finished'::character varying])::text[])))
);


ALTER TABLE public.task OWNER TO postgres;

--
-- Name: task_comment; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.task_comment (
    id integer NOT NULL,
    content character varying(255),
    author_id text NOT NULL,
    task_id integer NOT NULL
);


ALTER TABLE public.task_comment OWNER TO postgres;

--
-- Name: task_comment_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.task_comment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.task_comment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: task_executors; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.task_executors (
    task_id integer NOT NULL,
    executor_id text NOT NULL
);


ALTER TABLE public.task_executors OWNER TO postgres;

--
-- Name: task_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.task ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.task_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id character varying(255) NOT NULL,
    email character varying(255),
    first_name character varying(255),
    last_name character varying(255),
    username character varying(255)
);


ALTER TABLE public.users OWNER TO postgres;

--
-- Data for Name: task; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.task (id, description, header, priority, status, author_id) FROM stdin;
1	string	string	HIGH	InProgress	e8b5c496-87c3-401d-bfc3-0316c722ebdb
\.


--
-- Data for Name: task_comment; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.task_comment (id, content, author_id, task_id) FROM stdin;
\.


--
-- Data for Name: task_executors; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.task_executors (task_id, executor_id) FROM stdin;
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users (id, email, first_name, last_name, username) FROM stdin;
e8b5c496-87c3-401d-bfc3-0316c722ebdb	egorapotcha@gmail.com			admin
54313433-94d0-4e73-92f9-9c3418fa03a5	alice@gmail.com	Egor	Senkevich	user
\.


--
-- Name: task_comment_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.task_comment_id_seq', 1, false);


--
-- Name: task_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.task_id_seq', 1, true);


--
-- Name: task_comment task_comment_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.task_comment
    ADD CONSTRAINT task_comment_pkey PRIMARY KEY (id);


--
-- Name: task_executors task_executors_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.task_executors
    ADD CONSTRAINT task_executors_pkey PRIMARY KEY (task_id, executor_id);


--
-- Name: task task_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.task
    ADD CONSTRAINT task_pkey PRIMARY KEY (id);


--
-- Name: users uk6dotkott2kjsp8vw4d0m25fb7; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: task_comment fk6ha3x8pukpvrhtrgualofuvx8; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.task_comment
    ADD CONSTRAINT fk6ha3x8pukpvrhtrgualofuvx8 FOREIGN KEY (author_id) REFERENCES public.users(id);


--
-- Name: task_executors fkci103bvnpa0onnh73487j8207; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.task_executors
    ADD CONSTRAINT fkci103bvnpa0onnh73487j8207 FOREIGN KEY (executor_id) REFERENCES public.users(id);


--
-- Name: task_executors fkh3ia2j6xsoe602vvm8dbupep8; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.task_executors
    ADD CONSTRAINT fkh3ia2j6xsoe602vvm8dbupep8 FOREIGN KEY (task_id) REFERENCES public.task(id);


--
-- Name: task fknu4tbtolc8avjgstax6sk0woe; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.task
    ADD CONSTRAINT fknu4tbtolc8avjgstax6sk0woe FOREIGN KEY (author_id) REFERENCES public.users(id);


--
-- Name: task_comment fkpoxt1sd4otmq9p94rp1atkgs7; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.task_comment
    ADD CONSTRAINT fkpoxt1sd4otmq9p94rp1atkgs7 FOREIGN KEY (task_id) REFERENCES public.task(id);


--
-- PostgreSQL database dump complete
--

